### ISSUE TITLE
Error when adding a macro to the RTE

### ISSUE THREAD

**Issue by Dinc** [leekelleher/umbraco-ditto#14]
Im getting a YSOD error on "Save and Publish" after adding a macro into the RTE. (I've tried on a couple of sites with basic macros and it seems to be related to Ditto).

When I remove the following AppStartup code, the error goes away.

```c#
public class AppStartup : ApplicationEventHandler {
	protected override void ApplicationStarting(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext) {
		//Add ditto factory
		var types = PluginManager.Current.ResolveTypes<PublishedContentModel>();
		var factory = new DittoPublishedContentModelFactory(types);
		PublishedContentModelFactoryResolver.Current.SetFactory(factory);
	}
}
```

This is the YSOD error:

```c#
Failed to retrieve data for content id 1163
Cannot render a macro when there is no current PublishedContentRequest.

at Umbraco.Web.UmbracoHelper.RenderMacro(String alias, IDictionary`2 parameters)
   at Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.&lt;&gt;c__DisplayClass7.&lt;RenderRteMacros&gt;b__1(String macroAlias, Dictionary`2 macroAttributes)
   at Umbraco.Core.Macros.MacroTagParser.ParseMacros(String text, Action`1 textFoundCallback, Action`2 macroFoundCallback)
   at Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.RenderRteMacros(String source, Boolean preview)
   at Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.ConvertDataToSource(PublishedPropertyType propertyType, Object source, Boolean preview)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.XmlPublishedProperty.&lt;.ctor&gt;b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Umbraco.Web.PublishedCache.XmlPublishedCache.XmlPublishedProperty.&lt;.ctor&gt;b__1()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Umbraco.Web.PublishedCache.XmlPublishedCache.XmlPublishedProperty.get_Value()
   at Our.Umbraco.Ditto.PublishedContentExtensions.As(IPublishedContent content, Type type, Action`1 convertingType, Action`1 convertedType)
   at Our.Umbraco.Ditto.DittoPublishedContentModelFactory.&lt;&gt;c__DisplayClass4.&lt;.ctor&gt;b__1(IPublishedContent x)
   at Our.Umbraco.Ditto.DittoPublishedContentModelFactory.&lt;&gt;c__DisplayClass7.&lt;CreateModel&gt;b__6()
   at Umbraco.Core.Cache.HttpRequestCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem)
   at Our.Umbraco.Ditto.DittoPublishedContentModelFactory.CreateModel(IPublishedContent content)
   at Umbraco.Core.Models.PublishedContent.PublishedContentExtensionsForModels.CreateModel(IPublishedContent content)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.XmlPublishedContent.InitializeStructure()
   at Umbraco.Web.PublishedCache.XmlPublishedCache.XmlPublishedContent..ctor(XmlNode xmlNode, Boolean isPreviewing)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.ConvertToDocument(XmlNode xmlNode, Boolean isPreviewing)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.GetById(UmbracoContext umbracoContext, Boolean preview, Int32 nodeId)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.DetermineRouteById(UmbracoContext umbracoContext, Boolean preview, Int32 contentId)
   at Umbraco.Web.PublishedCache.XmlPublishedCache.PublishedContentCache.GetRouteById(UmbracoContext umbracoContext, Boolean preview, Int32 contentId)
   at Umbraco.Web.Routing.DefaultUrlProvider.GetUrl(UmbracoContext umbracoContext, Int32 id, Uri current, UrlProviderMode mode)
   at Umbraco.Web.Routing.UrlProvider.&lt;&gt;c__DisplayClass3.&lt;GetUrl&gt;b__0(IUrlProvider provider)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Umbraco.Web.Routing.UrlProvider.GetUrl(Int32 id, Uri current, UrlProviderMode mode)
   at Umbraco.Web.Routing.UrlProvider.GetUrl(Int32 id)
   at Umbraco.Web.Routing.UrlProviderExtensions.GetContentUrls(IContent content)
   at lambda_method(Closure , IContent )
   at AutoMapper.DelegateBasedResolver`2.Resolve(ResolutionResult source)
   at AutoMapper.PropertyMap.&lt;ResolveValue&gt;b__6(ResolutionResult current, IValueResolver resolver)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at AutoMapper.PropertyMap.ResolveValue(ResolutionContext context)
   at AutoMapper.Mappers.TypeMapObjectMapperRegistry.PropertyMapMappingStrategy.MapPropertyValue(ResolutionContext context, IMappingEngineRunner mapper, Object mappedObject, PropertyMap propertyMap)
```

Any ideas on whats causing the error?

Let me know if you need any more details / logs.

**Comment by leekelleher** [comment]
Closing. Fixed in #15

**Comment by mzajkowski** [comment]
Weird, cause I'm getting this error on new version of Ditto and Umbraco 7.3.4. When we have any macros inside RTE it fails to convert it to models outside the Razor views (in business logic for example). Any tips or workaround suggestions?

**Comment by leekelleher** [comment]
@mzajkowski - could you open a new issue for this one please?

I suspect it's not the exact same issue - this one only happened when using the `DittoPublishedContentModelFactory`.

**Comment by mzajkowski** [comment]
@leekelleher ok, will do that. Just to inform you and other: problem is stopped when RTE property is marked as virtual.

**Comment by CasperTDK** [comment]
It seems to be happening again:

[InvalidOperationException: The UmbracoPage object has not been initialized yet.]
   Umbraco.Web.UmbracoComponentRenderer.RenderMacro(String alias, IDictionary`2 parameters) +179
   Umbraco.Web.PropertyEditors.ValueConverters.<>c__DisplayClass7.<RenderRteMacros>b__1(String macroAlias, Dictionary`2 macroAttributes) +280
   Umbraco.Core.Macros.MacroTagParser.ParseMacros(String text, Action`1 textFoundCallback, Action`2 macroFoundCallback) +726
   Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.RenderRteMacros(String source, Boolean preview) +327
   Umbraco.Web.PropertyEditors.ValueConverters.RteMacroRenderingValueConverter.ConvertDataToSource(PublishedPropertyType propertyType, Object source, Boolean preview) +90
   Umbraco.Web.PublishedCache.XmlPublishedCache.XmlPublishedProperty.get_Value() +70
   Our.Umbraco.Ditto.UmbracoPropertyAttribute.GetPropertyValue(IPublishedContent content, String umbracoPropertyName, Boolean recursive) +111
   Our.Umbraco.Ditto.UmbracoPropertyAttribute.ProcessValue() +484
   Our.Umbraco.Ditto.DittoCacheableAttribute.GetCacheItem(DittoCacheContext cacheContext, Func`1 refresher) +508
   Our.Umbraco.Ditto.PublishedContentExtensions.DoGetProcessedValue(IPublishedContent content, CultureInfo culture, Type targetType, PropertyInfo propertyInfo, PropertyDescriptor propertyDescriptor, Type defaultProcessorType, IEnumerable`1 processorContexts) +1108
   Our.Umbraco.Ditto.PublishedContentExtensions.GetProcessedValue(IPublishedContent content, CultureInfo culture, Type targetType, PropertyInfo propertyInfo, Object instance, Type defaultProcessorType, IEnumerable`1 processorContexts) +633
   Our.Umbraco.Ditto.PublishedContentExtensions.ConvertContent(IPublishedContent content, Type type, CultureInfo culture, Object instance, IEnumerable`1 processorContexts, Action`1 onConverting, Action`1 onConverted) +1929
   Our.Umbraco.Ditto.PublishedContentExtensions.As(IPublishedContent content, Type type, CultureInfo culture, Object instance, IEnumerable`1 processorContexts, Action`1 onConverting, Action`1 onConverted) +599
   Our.Umbraco.Ditto.PublishedContentExtensions.As(IPublishedContent content, CultureInfo culture, T instance, IEnumerable`1 processorContexts, Action`1 onConverting, Action`1 onConverted) +103
   Our.Umbraco.Ditto.RenderModelExtensions.As(RenderModel model, IEnumerable`1 processorContexts, Action`1 onConverting, Action`1 onConverted) +261

**Comment by leekelleher** [comment]
@CasperTDK Are you using the `DittoPublishedContentModelFactory`?  Also which versions of Ditto & Umbraco please? (I'm assuming latest)

**Comment by CasperTDK** [comment]
@leekelleher I was too quick to judge. A custom call of PublishedContentRequest had snuck into the project. Your fix is working perfectly and you can close this again. Sorry!

**Comment by leekelleher** [comment]
@CasperTDK No worries, glad that it wasn't this problem. ☺️
